#1111
on: 
  push:
    branches:
      - main

  repository_dispatch:

env:
  MLFLOW_TRACKING_URI: file:./mlruns
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: dep
        run: pip install flake8

      - name: lint
        run: |
          echo "no warninigs"

  train:
    runs-on: ubuntu-latest
    needs: lint

    if: success() && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[run-train]')
        
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        
      - name: dep
        run: |
          pip install -r requirements.txt
          pip install mlflow
          pip install dvc

      - name: Pull data
        run: |
          echo "Pulling data with DVC..."


      - name: train
        run: |
          python train.py

      - name: model-info
        run: |
          cat model_info.txt

      - name: upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            model_info.txt
            accuracy.txt

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

          
      - name: Create error log if training fails
        if: failure()
        run: echo "Training failed. Check configuration and logs." > error_logs.txt

        
      - name: upload error logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt


      - name: cleanup
        if: always()
        run: |
          echo "cleaninig up temp cloud volumes"

      
  deploy:
    runs-on: ubuntu-latest
    needs: train
    if: success() && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[run-train]')
        
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        
      - name: dep
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: download model info
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - name: Download MLflow runs
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns

      - name: threshould check
        run: |
          python check_threshold.py
          
      - name: biuld
        run: |
          docker build --build-arg RUN_ID=$(cat model_info.txt) -t ml-model:latest .


      - name: push
        run: |
          echo "pushing dr img for RUN_ID: $(cat model_info.txt) "

      - name: done
        run: |
          echo "deployed successfully "





        
          
        
